spring:
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/java17-8
  username: root
  password: root
  type: com.alibaba.druid.pool.DruidDataSource
 thymeleaf:
  encoding: UTF-8
  suffix: .html
  mode: LEGACYHTML5
server:
 port: 8080